logs:
    dir_logs: logs/vqa/
annotations:
    type: "vqa"
    dir: /home/ubuntu/data_vqa/Annotations
    questions_dir: /home/ubuntu/data_vqa/Annotations/questions
    top_ans: 3000
    max_length: 40
    min_count_word: 0
    path_vocabs: /home/ubuntu/prepro_data/vqa/vocabs.json
images:
    dir: /home/ubuntu/data_vqa/Images
    dir_prefix: COCO_train2014_000000
    arch: ResNet152
    mode: attention
    img_size: 448
    preprocess_batch_size: 32
    preprocess_data_workers: 4
    path_features: /home/ubuntu/prepro_data/vqa/image_features
    preprocessed: False
    trainable: True
    augmentation:
        do_crop: false
        crop_scale: [0.6, 1.0]
        crop_ratio: [0.75, 1.33]

model:
# Could be added new architectures and hyper-parameters like activations etc
    pretrained_model:  #./logs/... # leave empty if no pretrained model is available
    seq2vec:
        dropout: 0.25
        emb_size: 300
    pooling:
        dim_v: 2048
        dim_q: 512 # 1024
        dim_h: 512 # 1024
        dropout_v: 0.5
        dropout_q: 0.5
    classifier:
        dropout: 0.5
    attention:
        glimpses: 2
        mid_features: 512
        dropout: 0.5
training:
    train_split: train
    lr: 0.001
    batch_size: 32
    epochs: 50
    data_workers: 8
    patience: 5

prediction:
    model_path: ./logs/vqa/2020-10-28_18:54:09/best_accuracy_log.pth
    split: test
    submission_file: ./predictions/default_pred.json

